### ISSUE TITLE
Contact 

### ISSUE THREAD

**Issue by Fragmon** [realengineerbo/stepper-stresser#1]
Thank you very much for your video. I am Sorry for opening the issue but you dont provide contact Information. Can you share your stl files for the mount of the stepper, idler, and weight? I would try this setup with different stepper.

Thank you very much. I will Credit you and Post the conclusion here.

**Comment by honboxuan** [comment]
Hello, did you also leave comments on YouTube asking for the CAD files? You should be able to get contact information from the channel information.

I have the STEP file prepared, but I'm away for business at the moment. Will upload the file here at the end of the week.

There's an upcoming video where I test and compare a range of stepper motors too, if you're interested.

**Comment by honboxuan** [comment]
[linear_assembly_585.zip](https://github.com/user-attachments/files/15848462/linear_assembly_585.zip)

Here's the STEP file as requested. There might be inaccuracies in the step files, so please use with caution.
